CREATE TABLE SKI (
    SKI_ID INTEGER GENERATED ALWAYS AS IDENTITY CONSTRAINT SKI_PK PRIMARY KEY,
    BRAND VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ARTICLE VARCHAR(25) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRICE DECIMAL(10, 2) NOT NULL
);

CREATE TABLE SKI_BOOT (
    SKI_BOOT_ID INTEGER GENERATED ALWAYS AS IDENTITY CONSTRAINT SKI_BOOT_PK PRIMARY KEY,
    BRAND VARCHAR(50) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    ARTICLE VARCHAR(25) NOT NULL,
    FLEX_INDEX INTEGER NOT NULL,
    MIN_SIZE DECIMAL(5,1) NOT NULL,
    MAX_SIZE DECIMAL(5,1) NOT NULL,
    DESCRIPTION VARCHAR(255),
    COLOR VARCHAR(50),
    PRICE DECIMAL(10, 2) NOT NULL
);
